name: js-warz-api

services:
  database:
    image: postgres:16.4-alpine
    ports:
      - 54325:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: js_warz
